base_homepage:
    path:     /{_locale}
    defaults: { _controller: BaseBundle:Default:index, _locale: es }
    requirements:
        _locale: es|en

user_homepage:
    path:     /{_locale}/userhome/
    defaults: { _controller: BaseBundle:User:userhome, _locale: es }
    requirements:
        _locale: es|en

registration:
    path:     /{_locale}/register
    defaults: { _controller: BaseBundle:Registration:register, _locale: es }
    requirements:
        _locale: es|en

login:
    path:     /login
    defaults: { _controller: BaseBundle:Default:index, _locale: es }

partida_home:
    path:     /{_locale}/userhome/{id_partida}
    defaults: { _controller: BaseBundle:Partida:partida, _locale: es }
    requirements: { id_partida: "\d+", _locale: es|en }

partida_register:
    path:     /{_locale}/userhome/register/{id_partida}
    defaults: { _controller: BaseBundle:Partida:partidaRegister, _locale: es }
    requirements: { id_partida: "\d+", _locale: es|en }

user_profile:
    path:     /{_locale}/userhome/{id_partida}/{username}
    defaults: { _controller: BaseBundle:Partida:jugador, _locale: es }
    requirements: { id_partida: "\d+", _locale: es|en }

user_profile_my:
    path:     /{_locale}/userhome/profile
    defaults: { _controller: BaseBundle:User:profile, _locale: es }
    requirements: { _locale: es|en }

create_deal:
    path:     /{_locale}/userhome/create_deal
    defaults: { _controller: BaseBundle:Partida:createDeal, _locale: es }
    requirements: { _locale: es|en }
    methods: [POST]

accept_reject_deal:
    path:     /{_locale}/userhome/accept_reject_deal
    defaults: { _controller: BaseBundle:Partida:acceptReject, _locale: es }
    requirements: { _locale: es|en }
    methods: [POST]

delete_deal:
    path:     /{_locale}/userhome/delete_deal
    defaults: { _controller: BaseBundle:Partida:deleteDeal, _locale: es }
    requirements: { _locale: es|en }
    methods: [POST]


admin_homepage:
    path:     /{_locale}/adminhome/
    defaults: { _controller: BaseBundle:Admin:adminHome, _locale: es }
    requirements: { _locale: es|en }

new_game:
    path:     /{_locale}/adminhome/new
    defaults: { _controller: BaseBundle:Admin:newGame, _locale: es }
    requirements: { _locale: es|en }

game_statistics:
    path:     /{_locale}/adminhome/stats/{id_partida}
    defaults: { _controller: BaseBundle:Admin:statistics, _locale: es }
    requirements: {id_partida: "\d+", _locale: es|en }

statistics_download_ranking:
    path:     /{_locale}/adminhome/stats/{id_partida}/download/
    defaults: { _controller: BaseBundle:Admin:rankingDownload, _locale: es }
    requirements: {id_partida: "\d+", _locale: es|en }

distribute_beans:
    path:     /{_locale}/adminhome/distribute/{id_partida}
    defaults: { _controller: BaseBundle:Admin:distributeBeans, _locale: es }
    requirements: {id_partida: "\d+", _locale: es|en }

change_password:
    path:     /{_locale}/password
    defaults: { _controller: BaseBundle:User:changePassword, _locale: es }
    requirements:
        _locale: es|en
    methods: [POST]