#    base.example:
#        class: BaseBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    app.form.registration:
        class: BaseBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: baseBundle_registration }
